// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sfnifgnevvoxceiqjrdi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNmbmlmZ25ldnZveGNlaXFqcmRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0MzI0NDEsImV4cCI6MjA2MDAwODQ0MX0.s5l7nU39_QYsETZMJr6v4iAhy8ocR8a6F9y8irFAEvQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);